### ISSUE TITLE
imq with Kernel 4.4.25 and grsecurity

### ISSUE THREAD

**Issue by amuerdter** [imq/linuximq#47]
compile kernel 4.4.25 with grsecurity and imq patch 4.4.5 failed.
compile kernel without grsecurity patch is working.

---snip---
drivers/net/imq.c:749:29: error: constified variable ‘imq_link_ops’ placed into writable section ".data..read_mostly"
 static struct rtnl_link_ops imq_link_ops __read_mostly = {
                             ^
scripts/Makefile.build:264: recipe for target 'drivers/net/imq.o' failed
make[2]: **\* [drivers/net/imq.o] Error 1
scripts/Makefile.build:403: recipe for target 'drivers/net' failed
make[1]: **\* [drivers/net] Error 2
Makefile:963: recipe for target 'drivers' failed
make: **\* [drivers] Error 2
make: **\* Waiting for unfinished jobs....
---snip---

imq with grsecurity compiles on kernel 4.4.21 without problems.
